# Generated by Django 3.2.9 on 2021-11-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='total_mark',
        ),
    ]
