# Generated by Django 3.2.9 on 2021-11-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_mark_total_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='total_marks',
            field=models.IntegerField(null=True),
        ),
    ]
