# Generated by Django 3.2.9 on 2021-11-06 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0003_mark_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reporting_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teacher'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
